### PR TITLE
Consider Fan service for additional icons

### PR DESCRIPTION
**Pull request by drewcovi**
Fanv2 seems to be out there to support some of the more advanced fans like BigAss Fans that have swinging properties, however this comes at the expense of some customizations within the Home app.

This resolves Issue https://github.com/jvmahon/homebridge-hubitat/issues/9

### CODE REVIEW

**Comment by drewcovi** [comment]
@jvmahon concerns or thoughts here? I have a ton of Leviton fan controllers, but I’d rather use your plugin than form 🙂

**Comment by drewcovi** [comment]
@jvmahon rolled back to Fanv2 service, but hoping we can include support for FanControl as this appears to be the preferred direction from the hub.

This is critical for my uses as only the Leviton driver reports back to the hub, and the Leviton driver only includes FanControl (which drives the UI for speed selection)

https://community.hubitat.com/t/leviton-fan-controller-needs-switchlevel/53913
https://docs.hubitat.com/index.php?title=Driver_Capability_List#FanControl

**Comment by jvmahon** [comment]
The problem with using "FanControl" is that HomeKit uses a percentage-based (0-100) speed control mechanism, rather than a Choose 1 of X type mechanism. I'm also adding a comment about this on the Leviton community forum that you cited.

**Comment by drewcovi** [comment]
@jvmahon great point. clearly for FanControl, we'd also need to establish a mapping and then round to  those values. I can take a pass at it and close this for now. Clearly drivers are all over the map. So the more flexible this solution can be the better.

**Comment by jvmahon** [comment]
The interim solution that could be coded would be as follows:

- If a device has FanControl as well as SwitchLevel, then use the SwitchLevel control to control the fan.
- If a device has FanControl but not SwitchLevel, then look at the FanControl "speed" attribute and see which of the attributes are supported ("low","medium-low","medium","medium-high","high"). Some fans may only support low, medium, high. If the driver was properly implemented, I believe its "speed" attribute should only have attributes it can support.
- Then create a mapping from the HomeKit percentage values to the FanControl values by breaking down the percentage ranges into sub-ranges that get associated with low, medium, high, etc.
- Then in the code that processes a HomeKit "set" value from the slider, you would have to map from the percentage to the FanControl value each time the slider is changed. Similarly, if the change originated on the Hubitat side, you'd need to do a mapping in the reverse direction from the Hubitat low / medium / high to a % value to report to HomeKit.

The realize that the Hubitat attributes are often so vaguely defined and specified that different fan controllers may allocate the ranges differently and may not set the "speed" attribute to correctly reflect the speeds truly supported, so post things on the forum hoping for a correction which may never come.

So I decided to just stick  with the "SwitchLevel" attribute instead.

One other approach would be to create a "virtual" device on Hubitat which would have a percentage-based control that you connect to the Homebridge plugin and has code to map to and control the "FanSpeed" based control.

**Comment by drewcovi** [comment]
@jvmahon absolutely. I pulled something similar together for [homebridge-vera](https://github.com/damianxd/homebridge-vera) complete with rounding.

really appreciate the work here.

thoughts on using **Fan** service for items exclusively with **FanControl**? support in HomeKit won't go away even if it's obsolete (hardware in the field already has it). it would seem to align with legacy AC motors.

**Comment by jvmahon** [comment]
Using the "Fan" service might make sense for fans with FanControl - it would allow two separate logic blocks to be implemented.  I'll take a look - but it may be a week or so. I'm re-opening this comment so that I remember to look.

**Comment by drewcovi** [comment]
@jvmahon glad to help out as well (if the kids ever give me a break). got about 50 z-wave devices across the spectrum, so always glad to lend an assist on device type tests as well.

**Comment by jvmahon** [comment]
FYI - I've added code to control fans that have the "FanControl" Capability but NOT the "SwitchLevel" Capability.  I think this is what you needed for your fan controller. I have not tested this code, so let me know if your fan controller now works and is adjustable.  

See Section 5.A, last paragraph, of the Readme page. Let me know if this works for you.

As an FYI, the new code is at lines 127-162 of the file "Lib/Setup LightsFansPlugs.js"

**Comment by drewcovi** [comment]
@jvmahon you’re a hero. Any chance that included delineation between Fan and Fanv2? I’ll gladly pull switchlevel from my custom driver if it means getting the classic ceiling fan animated icons back in the Home app 🙂. Thanks as always for the great work here.

**Comment by jvmahon** [comment]
No, I didn't include that other change to Fan instead of FanV2. I may investigate doing so in the future, but I think the change I made solved our main problem (at least I hope it did), so I'm closing this comment.

**Pull request closed without merging**
